name: Test action without search input
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action
        uses: ./
        env:
          COOL: "test value"
        with:
          working-directory: testdir
          fail_on_missing_variables: "true"
      - name: Test replaced files matches expected content
        working-directory: testdir
        run: |

          #test function
          function test_content {
              path=$1
              expected=$2
              actual=$(cat $path)
              if [[ "$actual" != "$expected" ]]; then
                  echo "Content does not match ! Expected '$expected' but got '$actual'"
                  exit 1
              fi
          }

          test_content "not-replaced.txt" "test test value"
          test_content "replaced/test.txt" "test test value"
          test_content "replaced/test1.txt" "test test value"
          test_content "replaced/replaced2/test2.txt" "test test value"
          test_content "replaced/replaced2/notreplaced/replaced.yaml" "test: test value"
          test_content "replaced/replaced2/test.yaml" "test: test value"
          test_content "replaced/replaced2/replace.me" "test test value"
